namespace EasyChallenges.Models.Templates;

using RogueGenesia.Data;

public enum ArtifactTemplate
{
    None = EArtifact.None,
    SoulGauntlet = EArtifact.SoulGauntlet,
    MagnifyingGlass = EArtifact.MagnifyingGlass,
    GilgameshRing = EArtifact.GilgameshRing,
    GilgameshCrown = EArtifact.GilgameshCrown,
    GilgameshSeal = EArtifact.GilgameshSeal,
    MidasSword = EArtifact.MidasSword,
    TrainingWeight = EArtifact.TrainingWeight,
    PersonalTrainer = EArtifact.PersonalTrainer,
    CheatingHand = EArtifact.CheatingHand,
    PhoenixTotem = EArtifact.PhoenixTotem,
    PocketHealer = EArtifact.PocketHealer,
    MartyrCloak = EArtifact.MartyrCloak,
    SageLeaf = EArtifact.SageLeaf,
    WindLace = EArtifact.WindLace,
    GlassSword = EArtifact.GlassSword,
    ChronosLace = EArtifact.ChronosLace,
    HolyCross = EArtifact.HolyCross,
    OuroborosNecklace = EArtifact.OuroborosNecklace,
    MithrilCompass = EArtifact.MithrilCompass,
    AdamantiteRod = EArtifact.AdamantiteRod,
    SacredSword = EArtifact.SacredSword,
    LightningBoots = EArtifact.LightningBoots,
    CursedBelt = EArtifact.CursedBelt,
    HermesHood = EArtifact.HermesHood,
    ChampionBracer = EArtifact.ChampionBracer,
    BhikkhuPearl = EArtifact.BhikkhuPearl,
    CowardSaphir = EArtifact.CowardSaphir,
    BattleRuby = EArtifact.BattleRuby,
    ChickenStatue = EArtifact.ChickenStatue,
    PorkStatue = EArtifact.PorkStatue,
    BeefStatue = EArtifact.BeefStatue,
    BlackSphereStatue = EArtifact.BlackSphereStatue,
    ShopKeeperPlate = EArtifact.ShopKeeperPlate,
    AdventurerLicence = EArtifact.AdventurerLicence,
    CollectionBook = EArtifact.CollectionBook,
    Dice = EArtifact.Dice,
    TrollBlood = EArtifact.TrollBlood,
    SheepStatue = EArtifact.SheepStatue,
    CorruptedCore = EArtifact.CorruptedCore,
    WanderHelmet = EArtifact.WanderHelmet,
}
